name: 'action-slscli'
description: 'a GitHub Action that allows you to use the serverless CLI inside of GitHub Actions'
inputs:
  command:
    description: 'Command to be run by Serverless'
    required: true
    default: '--version'
  working_directory:
    description: 'Directory in which Serverless should run'
    required: false
  should_throw:
    description: 'Define whether the action process should throw an error on Serverless error'
    required: false
    default: false
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
