name: 'action-slscli'
description: 'Gives user the ability to use the serverless CLI inside of a GitHub Action'
inputs:
  command:
    description: 'Command we pass to our serverless CLI'
    required: true
    default: '--version'
  working_directory:
    description: 'Directory in which we should run the CLI'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
